replicaCount: 5

image: ghcr.io/SatymSingh01/todo-devops-demo/todo-app
  repository: localhost:32000/todo-app
  tag: 2617a91a0a96c62219aed375bc09a06207ac719f
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
